### ISSUE TITLE
@Column inheritance

### ISSUE THREAD

**Issue by mikhaildudin-work** [influxdata/influxdb-client-java#98] opened 2020-03-29 11:32 UTC
Hi!
In the course of this issue
https://github.com/influxdata/influxdb-client-java/issues/89

I guess, the fix does not cover all cases.
Particularly, for my code, inheritance still does not work. Here it is:

```
public abstract class Metric {
    @Column(name = "source", tag = true)
    private String source;
}


@Measurement(name = "visitor")
public class Visitor extends Metric {
    @Column(name = "count")
    private long count;
}


public void writeData() {
    InfluxDBClient influxDBClient = ...
    writeApi = influxDBClient.getWriteApi();

    Metric metric = new Visitor();
    ...
    writeApi.writeMeasurement(WritePrecision.S, metric);
}
```

**Comment by bednar** [comment] 2020-04-02 06:04
Hi @mikhaildudin-work,

The issue is fixed in [1.7.0 milestone](https://github.com/influxdata/influxdb-client-java/milestone/10). 

If you would like to use a preview version use our snapshot build from repository: https://oss.sonatype.org/content/repositories/snapshots/

Regards

**Closed** 2020-04-02 06:04 UTC
Labels: bug
